image: node:20

before_script:
  - npm install

stages:
  - test
  - publish

test:
  stage: test
  script:
    - npm run test

# publish_to_gitlab_package_registry:
#   stage: publish
#   script:
#     - |
#       if [[ ! -f .npmrc ]]; then
#         echo 'No .npmrc found! Creating one now.'
#         {
#           echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
#           echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
#         } >> .npmrc
#       fi
#     - npm publish
#   only:
#     - main

publish_to_npm:
  stage: publish
  script:
    # create .npmrc file for npmjs.org registry with npm access token
    - echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > .npmrc
    # get version from package.json file
    - export LOCAL_PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
    # get version from npmjs.org registry
    - export REMOTE_PACKAGE_VERSION=$(npm view ${CI_PROJECT_NAME} version)
    # check if version is already published on npmjs.org registry
    - |
      if [[ "${LOCAL_PACKAGE_VERSION}" == "${REMOTE_PACKAGE_VERSION}" ]]; then
        echo "Version ${LOCAL_PACKAGE_VERSION} already published on npmjs.org registry. Skipping publish."
        exit 0
      fi
    # publish to npmjs.org registry
    - npm publish --access public
  only:
    - main
