image: node:20

before_script:
  - npm install

stages:
  - test
  - publish

test:
  stage: test
  script:
    - npm run test

publish_to_gitlab_package_registry:
  stage: publish
  script:
    - |
      if [[ ! -f .npmrc ]]; then
        echo 'No .npmrc found! Creating one now.'
        {
          echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
          echo "${CI_API_V4_URL#http*:}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
        } >> .npmrc
      fi
    - npm publish
  only:
    - main
# publish_to_npm:
#   stage: publish
#   script:
#     - echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > .npmrc
#     - npm publish
#   only:
#     - main
