image: node:20

before_script:
  - npm install

stages:
  - test
  - publish

test:
  stage: test
  script:
    - npm run test

publish_to_gitlab_package_registry:
  stage: publish
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_ACCESS_TOKEN}" > .npmrc
    - npm publish
  only:
    - main
# publish_to_npm:
#   stage: publish
#   script:
#     - echo "//registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN}" > .npmrc
#     - npm publish
#   only:
#     - main
